
#Yashodhan Prabhune,001220710,prabhune.y@husky.neu.edu
#Bhumika Khatri,001284560,khatri.bh@husky.neu.edu
#Aadesh Randeria,001224139,randeria.a@husky.neu.edu
#Siddhant Chandiwal,001286480,chandiwal.s@husky.neu.edu


language: java
jdk:
  - openjdk8

sudo: false
install: true

script:
  - ./gradlew build
  - ./gradlew war
  - ./gradlew test

after_success:
  - mkdir codedeploy
  - zip -r csye6225.zip build/libs/ROOT.war appspec.yml
  - ls -al
  - mv csye6225.zip codedeploy/
  - zip -r csye6225-lab.zip build/libs/ROOT.war appspec.yml
  - ls -al
  - mv csye6225-lab.zip codedeploy/
  - ls -al
  - pwd
  - cd codedeploy
  - ls -al
  - pwd

before_deploy:
  - cd ..

deploy:
  - provider: s3
    access_key_id: AKIAJFNCKCCGAY4XXC2A
    secret_access_key:
      secure: MpUCwz+N2aj6AS0JOKp0sjzTcZo2gl7HpSUBTgo+uMdGvlN4qpObarxJalwF4Dz9bK7LerAh7xR74trRjE6PGwD+v+urSDtjzFVx08ZDbOb3VpG5H72dyTROnLUQ21wY5E9CereQAgr7RL48mLxsh2emfkSOsHTW9fjxmIZST86pmBUBBiHiH8c6QKx/4Z+u2dmM/ZZOQ1sguA70ThpGXhyMoilLOb/kYCKczi6Wh9aIsEmNSDmBbqxxFs+8Xk8jqQlDZB8TJ7gvqk8rdcyb2HpojJ6djGCzVNRJh5W2QQCg6SljBQpHnogOP0Nl4lGJuc2rhtiwg7tCOIm2sGRYhxllDLsWL28+LFi8KC50VJtAArWkEzIhrVnlWFDrHUa4dchKRch3om4SDqSchMAHYfOoO0CfBVTzSR9jvcoIZ8uFXC7Eu8s0ckxnMvwUK4ioLuqWYuPnYpgQJzSmrvCGCAUFDzbh/l8Ynaphf7F+BKlQW+3v3stR8L/35+ivSAF44JSqeGctHfEp7ZFPzRW3yJ+ks2CWf40qc+qz1y4F82NYg39l3b9mjAt7AmGcNhVPfxb6lfyd+OeWCEuJrIcoh4U7lZ7XK/Mk8p5kNK2cUwNbjNL3FdD/boqR8rACABAFJ5lPpUBCj/+8EBlebRIK9pYWIAnrsWrMXFr5R+BD18g=
    local_dir: codedeploy
    bucket: code-deploy.aadeshranderia.me
    region: us-east-1
    skip_cleanup: true
    on:
      all_branches: true
  - provider: codedeploy
    access_key_id: AKIAJFNCKCCGAY4XXC2A
    bucket: code-deploy.aadeshranderia.me
    key: csye6225.zip
    bundle_type: zip
    application: csye6225
    deployment_group: csye6225
    region: us-east-1
    secret_access_key:
      secure: MpUCwz+N2aj6AS0JOKp0sjzTcZo2gl7HpSUBTgo+uMdGvlN4qpObarxJalwF4Dz9bK7LerAh7xR74trRjE6PGwD+v+urSDtjzFVx08ZDbOb3VpG5H72dyTROnLUQ21wY5E9CereQAgr7RL48mLxsh2emfkSOsHTW9fjxmIZST86pmBUBBiHiH8c6QKx/4Z+u2dmM/ZZOQ1sguA70ThpGXhyMoilLOb/kYCKczi6Wh9aIsEmNSDmBbqxxFs+8Xk8jqQlDZB8TJ7gvqk8rdcyb2HpojJ6djGCzVNRJh5W2QQCg6SljBQpHnogOP0Nl4lGJuc2rhtiwg7tCOIm2sGRYhxllDLsWL28+LFi8KC50VJtAArWkEzIhrVnlWFDrHUa4dchKRch3om4SDqSchMAHYfOoO0CfBVTzSR9jvcoIZ8uFXC7Eu8s0ckxnMvwUK4ioLuqWYuPnYpgQJzSmrvCGCAUFDzbh/l8Ynaphf7F+BKlQW+3v3stR8L/35+ivSAF44JSqeGctHfEp7ZFPzRW3yJ+ks2CWf40qc+qz1y4F82NYg39l3b9mjAt7AmGcNhVPfxb6lfyd+OeWCEuJrIcoh4U7lZ7XK/Mk8p5kNK2cUwNbjNL3FdD/boqR8rACABAFJ5lPpUBCj/+8EBlebRIK9pYWIAnrsWrMXFr5R+BD18g=
    wait-until-deployed: true

notifications:
  email:
    recipients:
      - chandiwal.s@husky.neu.edu
      - randeria.a@husky.neu.edu
      - prabhune.y@husky.neu.edu
      - khatri.bh@husky.neu.edu
    on_success: always
    on_failure: always
