
#Yashodhan Prabhune,001220710,prabhune.y@husky.neu.edu
#Bhumika Khatri,001284560,khatri.bh@husky.neu.edu
#Aadesh Randeria,001224139,randeria.a@husky.neu.edu
#Siddhant Chandiwal,001286480,chandiwal.s@husky.neu.edu


language: java
jdk:
  - openjdk8

sudo: false
install: true

script:
  - ./gradlew build
  - ./gradlew war
  - ./gradlew test

after_success:
  - mkdir codedeploy
  - zip -r csye6225-lab.zip build/libs/ROOT.war appspec.yml
  - ls -al
  - mv csye6225-lab.zip codedeploy/
  - ls -al
  - pwd
  - cd codedeploy
  - ls -al
  - pwd

before_deploy:
  - cd ..

deploy:
  - provider: s3
    access_key_id: AKIAI7SFOP22K5O2C7GQ
    secret_access_key:
      secure:  secure: nZ1hmxEj7TVBEi0JIg3W3zdbSYZGJ+4QG4IR9GwYJL//qni4ocTPDsCU/3WemYJWG9WmEwUNDbJpoufrweHy/2jnhhbaRiFAiccVnmVgiQfHHbwUASXc8+XXdZLrvquQJC9aHwae+Nj+jhUNPl0gWlbGlgKz/dYbBW6gts1idIbryq7nZukHo6nBJxQM0Bfofb24IE68hCFEl8J0ugvuu6RqrYXDPwWQvlhqmXi3c7A/PQvd7XitVXszJqXIB9jUqSOt8qtpvzJABy4QFocs4OcyZeWrWBk/hOlicjocNWqAy92oNUl12TyBIg5kRaCa9ibsW0NSjCRtl0YBm9e0qnH10I/HvIR8T0Tx2augpyC9Yg6DTi8KrTlKeoKQ0b1ykRdlXragGTP0dXukh03IeqEa5rAK5gNpzRsxKQq45LoiZ7mJxi20NfLuXYZ8fP880OASlAemo1FdGqdboz5FVNpgTt2b8G3hT6JgKFy3KT/mTy/wF2SMbWaEx26ZgtBH4Mj7i1y+0jCVKplLvn9T/KtCA5wnhOMD67dalwsVtUTHPjbMcdwlnQbIr/YXMFYfNmE1pdBPVN01yHL3JfZOKF8rz1dmi8JpBapi2YMqgcUoYBO1bcn81vwpK0pdf6ZgZMUcJZKHCt30x1AheBczmWHHhMjP3CIdUQEzszbHywM=
    local_dir: codedeploy
    bucket: code-deploy.bhumikakhatri.me
    region: us-east-1
    skip_cleanup: true
    on:
      all_branches: true
  - provider: codedeploy
    access_key_id: AKIAI7SFOP22K5O2C7GQ
    bucket: code-deploy.bhumikakhatri.me
    key: csye6225.zip
    bundle_type: zip
    application: csye6225
    deployment_group: csye6225
    region: us-east-1
    secret_access_key:
      secure:  secure: nZ1hmxEj7TVBEi0JIg3W3zdbSYZGJ+4QG4IR9GwYJL//qni4ocTPDsCU/3WemYJWG9WmEwUNDbJpoufrweHy/2jnhhbaRiFAiccVnmVgiQfHHbwUASXc8+XXdZLrvquQJC9aHwae+Nj+jhUNPl0gWlbGlgKz/dYbBW6gts1idIbryq7nZukHo6nBJxQM0Bfofb24IE68hCFEl8J0ugvuu6RqrYXDPwWQvlhqmXi3c7A/PQvd7XitVXszJqXIB9jUqSOt8qtpvzJABy4QFocs4OcyZeWrWBk/hOlicjocNWqAy92oNUl12TyBIg5kRaCa9ibsW0NSjCRtl0YBm9e0qnH10I/HvIR8T0Tx2augpyC9Yg6DTi8KrTlKeoKQ0b1ykRdlXragGTP0dXukh03IeqEa5rAK5gNpzRsxKQq45LoiZ7mJxi20NfLuXYZ8fP880OASlAemo1FdGqdboz5FVNpgTt2b8G3hT6JgKFy3KT/mTy/wF2SMbWaEx26ZgtBH4Mj7i1y+0jCVKplLvn9T/KtCA5wnhOMD67dalwsVtUTHPjbMcdwlnQbIr/YXMFYfNmE1pdBPVN01yHL3JfZOKF8rz1dmi8JpBapi2YMqgcUoYBO1bcn81vwpK0pdf6ZgZMUcJZKHCt30x1AheBczmWHHhMjP3CIdUQEzszbHywM=
    wait-until-deployed: true

notifications:
  email:
    recipients:
      - chandiwal.s@husky.neu.edu
      - randeria.a@husky.neu.edu
      - prabhune.y@husky.neu.edu
      - khatri.bh@husky.neu.edu
    on_success: always
    on_failure: always
